- name: Disable the online tips
  hosts: windows
  tasks:
    - name: Disable Online Tips
      win_shell: "{{ lookup('file', '~/Server2016/files/disabletips.ps1')}}"

    - name: Set NetBIOS node type to P-node
      win_shell: "{{ lookup('file', '~/Server2016/files/changenetbiosnodetype.ps1')}}"

    - name: Remote host allows delegation of non-exportable credentials is set to enabled
      win_shell: "{{ lookup('file', '~/Server2016/files/creddelegation.ps1')}}"

    - name: Enable Disable Authenticated Proxy usage for connected user experience and Telemetry service
      win_shell: "{{ lookup('file', '~/Server2016/files/connecteduserexp.ps1')}}"

    - name: Ensure Allow Message Service Cloud Sync is set to Disabled
      win_shell: "{{ lookup('file', '~/Server2016/files/disablecloudsync.ps1')}}"

    - name: Block all consumer Microsoft account user authentication is set to Enabled
      win_shell: "{{ lookup('file', '~/Server2016/files/blockconsumermicrosoftaccount.ps1')}}"

    - name: Allow Cloud Search is set to disabled
      win_shell: "{{ lookup('file', '~/Server2016/files/disablecloudsearch.ps1')}}"