- name: Disable the online tips
  hosts: windows
  tasks:
    - name: Run a script
      win_shell: "{{ lookup('file', '~/Server2016/files/disabletips.ps1')}}"

    - name: Run a script
      win_shell: "{{ lookup('file', '~/Server2016/files/changenetbiosnodetype.ps1')}}"

    - name: Run a script
      win_shell: "{{ lookup('file', '~/Server2016/files/creddelegation.ps1')}}"

    - name: Run a script
      win_shell: "{{ lookup('file', '~/Server2016/files/connecteduserexp.ps1')}}"

    - name: Run a script
      win_shell: "{{ lookup('file', '~/Server2016/files/disablecloudsync.ps1')}}"

    - name: Run a script
      win_shell: "{{ lookup('file', '~/Server2016/files/blockconsumermicrosoftaccount.ps1')}}"

    - name: Run a script
      win_shell: "{{ lookup('file', '~/Server2016/files/disablecloudsearch.ps1')}}"